parameters:
  legacy.action_resolver:
    merge-records:
      index: action_module
      Step1: action_module
    import:
      index: import_module
      step1: import_module
      Last: import_module
