apiVersion: v1
kind: Service
metadata:
    name: cbmariadb
    labels:
       app: cbsuitecrm-app
spec:
    ports:
    - port: 3306
      name: cbmariadb
    clusterIP: None
    selector:
       app: cbsuitecrm-app