apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: cbmariadb
spec:
  selector:
      matchLabels:
       app: cbsuitecrm-app
  serviceName: "cbmariadb"
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        app: cbsuitecrm-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cbsuitemysql
        image: registry.redhat.io/rhel8/mariadb-103
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cbmariadb-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: cb_suitecrm
        - name: MYSQL_USER
          value: cbsuite_adm
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cbmariadb-secrets
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: cbmariadb
        volumeMounts:
        - name: cbmariadb-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: cbmariadb-data
    spec:
      storageClassName: netapp-file-standard
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi