<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditActionCheckerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Engine\LegacyHandler\ActionAvailabilityChecker\Checkers\AuditActionChecker' shared autowired service.
     *
     * @return \App\Engine\LegacyHandler\ActionAvailabilityChecker\Checkers\AuditActionChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/ActionAvailabilityChecker/ActionAvailabilityCheckerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/LegacyHandler/ActionAvailabilityChecker/Checkers/AuditActionChecker.php';

        return $container->privates['App\\Engine\\LegacyHandler\\ActionAvailabilityChecker\\Checkers\\AuditActionChecker'] = new \App\Engine\LegacyHandler\ActionAvailabilityChecker\Checkers\AuditActionChecker(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'LEGACYSESSID', 'PHPSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ?? ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] = new \App\Engine\LegacyHandler\LegacyScopeState())), ($container->services['session'] ?? $container->getSessionService()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? $container->getModuleNameMapperHandlerService()));
    }
}
