<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlertsDataHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\LegacyHandler\PresetDataHandlers\AlertsDataHandler' shared autowired service.
     *
     * @return \App\Data\LegacyHandler\PresetDataHandlers\AlertsDataHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/BaseListDataHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/ListDataHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/ListDataHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/PresetListDataHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/PresetDataHandlers/AlertsDataHandler.php';

        return $container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\AlertsDataHandler'] = new \App\Data\LegacyHandler\PresetDataHandlers\AlertsDataHandler(($container->privates['App\\Data\\LegacyHandler\\FilterMapper\\LegacyFilterMapper'] ?? $container->load('getLegacyFilterMapperService')), ($container->privates['App\\Data\\LegacyHandler\\RecordMapper'] ?? $container->load('getRecordMapperService')));
    }
}
