<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddNewConfigEntriesService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Service\Upgrade\Steps\AddNewConfigEntries' autowired service.
     *
     * @return \App\Install\Service\Upgrade\Steps\AddNewConfigEntries
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Upgrade/UpgradeStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Upgrade/Steps/AddNewConfigEntries.php';

        $container->factories['service_container']['App\\Install\\Service\\Upgrade\\Steps\\AddNewConfigEntries'] = function () use ($container) {
            return new \App\Install\Service\Upgrade\Steps\AddNewConfigEntries(($container->privates['App\\Install\\LegacyHandler\\Upgrade\\AddNewConfigEntriesHandler'] ?? $container->load('getAddNewConfigEntriesHandlerService')));
        };

        return $container->factories['service_container']['App\\Install\\Service\\Upgrade\\Steps\\AddNewConfigEntries']();
    }
}
