<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Action_GraphqlPlaygroundService extends App_KernelProdContainer
{
    /*
     * Gets the public 'api_platform.graphql.action.graphql_playground' shared service.
     *
     * @return \ApiPlatform\Core\GraphQl\Action\GraphQlPlaygroundAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/GraphQl/Action/GraphQlPlaygroundAction.php';

        return $container->services['api_platform.graphql.action.graphql_playground'] = new \ApiPlatform\Core\GraphQl\Action\GraphQlPlaygroundAction(($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService')), ($container->privates['api_platform.router'] ?? $container->getApiPlatform_RouterService()), true, '', NULL);
    }
}
