<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Authentication\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Authentication\\Controller\\SecurityController::nativeAuthLogin' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Authentication\\Controller\\SecurityController::nativeAuthSessionStatus' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Authentication\\Controller\\SecurityController::sessionStatus' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Engine\\Controller\\IndexController::index' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Engine\\Controller\\IndexController::loggedOut' => ['privates', '.service_locator.dbFJ5zg', 'get_ServiceLocator_DbFJ5zgService', true],
            'App\\Engine\\Controller\\IndexController::nativeAuth' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Authentication\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Authentication\\Controller\\SecurityController:nativeAuthLogin' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Authentication\\Controller\\SecurityController:nativeAuthSessionStatus' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Authentication\\Controller\\SecurityController:sessionStatus' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Engine\\Controller\\IndexController:index' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Engine\\Controller\\IndexController:loggedOut' => ['privates', '.service_locator.dbFJ5zg', 'get_ServiceLocator_DbFJ5zgService', true],
            'App\\Engine\\Controller\\IndexController:nativeAuth' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Authentication\\Controller\\SecurityController::login' => '?',
            'App\\Authentication\\Controller\\SecurityController::nativeAuthLogin' => '?',
            'App\\Authentication\\Controller\\SecurityController::nativeAuthSessionStatus' => '?',
            'App\\Authentication\\Controller\\SecurityController::sessionStatus' => '?',
            'App\\Engine\\Controller\\IndexController::index' => '?',
            'App\\Engine\\Controller\\IndexController::loggedOut' => '?',
            'App\\Engine\\Controller\\IndexController::nativeAuth' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Authentication\\Controller\\SecurityController:login' => '?',
            'App\\Authentication\\Controller\\SecurityController:nativeAuthLogin' => '?',
            'App\\Authentication\\Controller\\SecurityController:nativeAuthSessionStatus' => '?',
            'App\\Authentication\\Controller\\SecurityController:sessionStatus' => '?',
            'App\\Engine\\Controller\\IndexController:index' => '?',
            'App\\Engine\\Controller\\IndexController:loggedOut' => '?',
            'App\\Engine\\Controller\\IndexController:nativeAuth' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
