<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_DataPersisterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'api_platform.data_persister' shared service.
     *
     * @return \ApiPlatform\Core\DataPersister\ChainDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/Core/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/Core/DataPersister/ContextAwareDataPersisterInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/Core/DataPersister/ChainDataPersister.php';

        return $container->privates['api_platform.data_persister'] = new \ApiPlatform\Core\DataPersister\ChainDataPersister(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Process\\DataPersister\\ProcessDataPersister'] ?? $container->load('getProcessDataPersisterService'));
            yield 1 => ($container->privates['App\\Process\\DataPersister\\RecordDataPersister'] ?? $container->load('getRecordDataPersisterService'));
            yield 2 => ($container->privates['api_platform.doctrine.orm.data_persister'] ?? $container->load('getApiPlatform_Doctrine_Orm_DataPersisterService'));
        }, 3));
    }
}
