<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppStringsItemDataProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Languages\DataProvider\AppStringsItemDataProvider' shared autowired service.
     *
     * @return \App\Languages\DataProvider\AppStringsItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Languages/DataProvider/AppStringsItemDataProvider.php';

        return $container->privates['App\\Languages\\DataProvider\\AppStringsItemDataProvider'] = new \App\Languages\DataProvider\AppStringsItemDataProvider(($container->privates['App\\Languages\\LegacyHandler\\AppStringsHandler'] ?? $container->load('getAppStringsHandlerService')));
    }
}
