<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_CachePoolListService extends App_KernelProdContainer
{
    /*
     * Gets the private 'console.command.cache_pool_list' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Command\CachePoolListCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/framework-bundle/Command/CachePoolListCommand.php';

        $container->privates['console.command.cache_pool_list'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\CachePoolListCommand([0 => 'cache.app', 1 => 'cache.system', 2 => 'cache.validator', 3 => 'cache.serializer', 4 => 'cache.annotations', 5 => 'cache.property_info', 6 => 'doctrine.result_cache_pool', 7 => 'doctrine.system_cache_pool', 8 => 'cache.property_access', 9 => 'cache.rate_limiter', 10 => 'cache.security_expression_language', 11 => 'api_platform.cache.route_name_resolver', 12 => 'api_platform.cache.metadata.resource', 13 => 'api_platform.cache.metadata.resource.legacy', 14 => 'api_platform.cache.metadata.property.legacy', 15 => 'api_platform.cache.subresource_operation_factory', 16 => 'api_platform.graphql.cache.subscription', 17 => 'api_platform.cache.identifiers_extractor', 18 => 'shivas_versioning.cache.version']);

        $instance->setName('cache:pool:list');

        return $instance;
    }
}
