<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactSyncMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Contacts\Service\MassUpdate\ContactSyncMapper' shared autowired service.
     *
     * @return \App\Module\Contacts\Service\MassUpdate\ContactSyncMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/ModuleAwareRegistryItemInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/Service/MassUpdateDefinitionMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/LegacyHandler/FieldDefinitionsInjectorTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/Service/MassUpdate/MassUpdateFieldDefinitionsInjectorTrait.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Contacts/Service/MassUpdate/ContactSyncMapper.php';

        return $container->privates['App\\Module\\Contacts\\Service\\MassUpdate\\ContactSyncMapper'] = new \App\Module\Contacts\Service\MassUpdate\ContactSyncMapper(($container->privates['App\\ViewDefinitions\\Service\\FieldAliasMapper'] ?? $container->load('getFieldAliasMapperService')));
    }
}
