<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateTimeHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\DateTime\LegacyHandler\DateTimeHandler' shared autowired service.
     *
     * @return \App\DateTime\LegacyHandler\DateTimeHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/DateTime/LegacyHandler/DateTimeHandler.php';

        return $container->privates['App\\DateTime\\LegacyHandler\\DateTimeHandler'] = new \App\DateTime\LegacyHandler\DateTimeHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'LEGACYSESSID', 'PHPSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ?? ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] = new \App\Engine\LegacyHandler\LegacyScopeState())), $container->parameters['legacy.datetime_format_map'], ($container->services['session'] ?? $container->getSessionService()));
    }
}
