<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultModuleConfigMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\SystemConfig\LegacyHandler\DefaultModuleConfigMapper' shared autowired service.
     *
     * @return \App\SystemConfig\LegacyHandler\DefaultModuleConfigMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/SystemConfig/LegacyHandler/SystemConfigMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/SystemConfig/LegacyHandler/DefaultModuleConfigMapper.php';

        return $container->privates['App\\SystemConfig\\LegacyHandler\\DefaultModuleConfigMapper'] = new \App\SystemConfig\LegacyHandler\DefaultModuleConfigMapper(($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? $container->getModuleNameMapperHandlerService()));
    }
}
