<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultCurrencyConfigMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\SystemConfig\LegacyHandler\DefaultCurrencyConfigMapper' shared autowired service.
     *
     * @return \App\SystemConfig\LegacyHandler\DefaultCurrencyConfigMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/SystemConfig/LegacyHandler/SystemConfigMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/SystemConfig/LegacyHandler/DefaultCurrencyConfigMapper.php';

        return $container->privates['App\\SystemConfig\\LegacyHandler\\DefaultCurrencyConfigMapper'] = new \App\SystemConfig\LegacyHandler\DefaultCurrencyConfigMapper(($container->privates['App\\Currency\\LegacyHandler\\CurrencyHandler'] ?? $container->getCurrencyHandlerService()));
    }
}
