<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDismissAlertActionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\Service\RecordThreadItemActions\DismissAlertAction' shared autowired service.
     *
     * @return \App\Process\Service\RecordThreadItemActions\DismissAlertAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/RecordThreadItemActions/DismissAlertAction.php';

        return $container->privates['App\\Process\\Service\\RecordThreadItemActions\\DismissAlertAction'] = new \App\Process\Service\RecordThreadItemActions\DismissAlertAction(($container->privates['App\\Data\\LegacyHandler\\AlertHandler'] ?? $container->load('getAlertHandlerService')));
    }
}
