<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoritesHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\LegacyHandler\Favorites\FavoritesHandler' shared autowired service.
     *
     * @return \App\Module\LegacyHandler\Favorites\FavoritesHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/FavoriteProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Module/LegacyHandler/Favorites/FavoritesHandler.php';

        return $container->privates['App\\Module\\LegacyHandler\\Favorites\\FavoritesHandler'] = new \App\Module\LegacyHandler\Favorites\FavoritesHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'LEGACYSESSID', 'PHPSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ?? ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] = new \App\Engine\LegacyHandler\LegacyScopeState())), ($container->services['session'] ?? $container->getSessionService()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? $container->getModuleNameMapperHandlerService()));
    }
}
