<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldDefinitionItemDataProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\FieldDefinitions\DataProvider\FieldDefinitionItemDataProvider' shared autowired service.
     *
     * @return \App\FieldDefinitions\DataProvider\FieldDefinitionItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/DataProvider/FieldDefinitionItemDataProvider.php';

        return $container->privates['App\\FieldDefinitions\\DataProvider\\FieldDefinitionItemDataProvider'] = new \App\FieldDefinitions\DataProvider\FieldDefinitionItemDataProvider(($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService')));
    }
}
