<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinalizeClearSymfonyCacheService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Service\Upgrade\Steps\FinalizeClearSymfonyCache' autowired service.
     *
     * @return \App\Install\Service\Upgrade\Steps\FinalizeClearSymfonyCache
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Upgrade/UpgradeStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Upgrade/Steps/FinalizeClearSymfonyCache.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Cache/CacheBridge.php';

        $container->factories['service_container']['App\\Install\\Service\\Upgrade\\Steps\\FinalizeClearSymfonyCache'] = function () use ($container) {
            return new \App\Install\Service\Upgrade\Steps\FinalizeClearSymfonyCache(($container->privates['App\\Install\\Service\\Cache\\CacheBridge'] ?? ($container->privates['App\\Install\\Service\\Cache\\CacheBridge'] = new \App\Install\Service\Cache\CacheBridge(($container->services['kernel'] ?? $container->get('kernel', 1)), $container->targetDir.''))));
        };

        return $container->factories['service_container']['App\\Install\\Service\\Upgrade\\Steps\\FinalizeClearSymfonyCache']();
    }
}
