<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupedFieldDefinitionMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\FieldDefinitions\LegacyHandler\GroupedFieldDefinitionMapper' shared autowired service.
     *
     * @return \App\FieldDefinitions\LegacyHandler\GroupedFieldDefinitionMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/LegacyHandler/FieldDefinitionMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/LegacyHandler/GroupedFieldDefinitionMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/LegacyHandler/GroupedFieldDefinitionMapper.php';

        return $container->privates['App\\FieldDefinitions\\LegacyHandler\\GroupedFieldDefinitionMapper'] = new \App\FieldDefinitions\LegacyHandler\GroupedFieldDefinitionMapper($container->parameters['record.fields.grouped_fields_type_map']);
    }
}
