<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallExtensionAssetsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Command\InstallExtensionAssets' shared autowired service.
     *
     * @return \App\Install\Command\InstallExtensionAssets
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Command/InstallExtensionAssets.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/Extensions/ExtensionAssetCopyInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/Extensions/ExtensionAssetCopy.php';

        $container->privates['App\\Install\\Command\\InstallExtensionAssets'] = $instance = new \App\Install\Command\InstallExtensionAssets(($container->privates['App\\Engine\\Service\\Extensions\\ExtensionAssetCopy'] ?? ($container->privates['App\\Engine\\Service\\Extensions\\ExtensionAssetCopy'] = new \App\Engine\Service\Extensions\ExtensionAssetCopy(\dirname(__DIR__, 3)))));

        $instance->setName('scrm:extension-asset-install');

        return $instance;
    }
}
