<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyInlineEditFieldDefinitionMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\FieldDefinitions\LegacyHandler\LegacyInlineEditFieldDefinitionMapper' shared autowired service.
     *
     * @return \App\FieldDefinitions\LegacyHandler\LegacyInlineEditFieldDefinitionMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/LegacyHandler/FieldDefinitionMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/LegacyHandler/LegacyInlineEditFieldDefinitionMapper.php';

        return $container->privates['App\\FieldDefinitions\\LegacyHandler\\LegacyInlineEditFieldDefinitionMapper'] = new \App\FieldDefinitions\LegacyHandler\LegacyInlineEditFieldDefinitionMapper(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'LEGACYSESSID', 'PHPSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ?? ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] = new \App\Engine\LegacyHandler\LegacyScopeState())), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? $container->getModuleNameMapperHandlerService()), ($container->services['session'] ?? $container->getSessionService()));
    }
}
