<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyFilterMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\LegacyHandler\FilterMapper\LegacyFilterMapper' shared autowired service.
     *
     * @return \App\Data\LegacyHandler\FilterMapper\LegacyFilterMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/FilterMapper/LegacyFilterMapper.php';

        return $container->privates['App\\Data\\LegacyHandler\\FilterMapper\\LegacyFilterMapper'] = new \App\Data\LegacyHandler\FilterMapper\LegacyFilterMapper(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'LEGACYSESSID', 'PHPSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ?? ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] = new \App\Engine\LegacyHandler\LegacyScopeState())), ($container->services['session'] ?? $container->getSessionService()));
    }
}
