<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleMetadataItemDataProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Metadata\DataProvider\ModuleMetadataItemDataProvider' shared autowired service.
     *
     * @return \App\Metadata\DataProvider\ModuleMetadataItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Metadata/DataProvider/ModuleMetadataItemDataProvider.php';

        return $container->privates['App\\Metadata\\DataProvider\\ModuleMetadataItemDataProvider'] = new \App\Metadata\DataProvider\ModuleMetadataItemDataProvider(($container->privates['App\\Metadata\\Service\\ModuleMetadataProvider'] ?? $container->load('getModuleMetadataProviderService')));
    }
}
