<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProspectsEmailOptoutMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Prospects\Service\MassUpdate\ProspectsEmailOptoutMapper' shared autowired service.
     *
     * @return \App\Module\Prospects\Service\MassUpdate\ProspectsEmailOptoutMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/ModuleAwareRegistryItemInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/Service/MassUpdateDefinitionMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/LegacyHandler/FieldDefinitionsInjectorTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/Service/MassUpdate/MassUpdateFieldDefinitionsInjectorTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/Service/MassUpdate/EmailOptoutMapper.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Prospects/Service/MassUpdate/ProspectsEmailOptoutMapper.php';

        return $container->privates['App\\Module\\Prospects\\Service\\MassUpdate\\ProspectsEmailOptoutMapper'] = new \App\Module\Prospects\Service\MassUpdate\ProspectsEmailOptoutMapper(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'LEGACYSESSID', 'PHPSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ?? ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] = new \App\Engine\LegacyHandler\LegacyScopeState())), ($container->services['session'] ?? $container->getSessionService()), ($container->privates['App\\ViewDefinitions\\Service\\FieldAliasMapper'] ?? $container->load('getFieldAliasMapperService')));
    }
}
