<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordListHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\LegacyHandler\RecordListHandler' shared autowired service.
     *
     * @return \App\Data\LegacyHandler\RecordListHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/RecordListProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/RecordListHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/BaseListDataHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/ListDataHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/ListDataHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/PresetListDataHandlers.php';

        return $container->privates['App\\Data\\LegacyHandler\\RecordListHandler'] = new \App\Data\LegacyHandler\RecordListHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'LEGACYSESSID', 'PHPSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ?? ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] = new \App\Engine\LegacyHandler\LegacyScopeState())), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? $container->getModuleNameMapperHandlerService()), new \App\Data\LegacyHandler\ListDataHandler(($container->privates['App\\Data\\LegacyHandler\\FilterMapper\\LegacyFilterMapper'] ?? $container->load('getLegacyFilterMapperService')), ($container->privates['App\\Data\\LegacyHandler\\RecordMapper'] ?? $container->load('getRecordMapperService'))), new \App\Data\LegacyHandler\PresetListDataHandlers(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\AlertsDataHandler'] ?? $container->load('getAlertsDataHandlerService'));
            yield 1 => ($container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\HistoryTimelineDataHandler'] ?? $container->load('getHistoryTimelineDataHandlerService'));
            yield 2 => ($container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\SubpanelDataHandler'] ?? $container->load('getSubpanelDataHandlerService'));
        }, 3)), ($container->services['session'] ?? $container->getSessionService()));
    }
}
