<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunMigrationsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Service\Upgrade\Steps\RunMigrations' autowired service.
     *
     * @return \App\Install\Service\Upgrade\Steps\RunMigrations
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Upgrade/UpgradeStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Upgrade/Steps/RunMigrations.php';

        $container->factories['service_container']['App\\Install\\Service\\Upgrade\\Steps\\RunMigrations'] = function () use ($container) {
            return new \App\Install\Service\Upgrade\Steps\RunMigrations(($container->privates['App\\Install\\Service\\Migrations\\MigrationBridge'] ?? $container->load('getMigrationBridgeService')));
        };

        return $container->factories['service_container']['App\\Install\\Service\\Upgrade\\Steps\\RunMigrations']();
    }
}
