<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSamlUserFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'saml_user_factory' shared autowired service.
     *
     * @return \App\Security\Saml\AppSamlUserFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/hslavich/oneloginsaml-bundle/Security/User/SamlUserFactoryInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Logging/Services/AppLoggingTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/Saml/AppSamlUserFactory.php';

        return $container->services['saml_user_factory'] = new \App\Security\Saml\AppSamlUserFactory(($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->getUserHandlerService()), NULL, ($container->services['monolog.logger.auth'] ?? $container->load('getMonolog_Logger_AuthService')));
    }
}
