<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Listener_JsonLoginLdap_MainService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.listener.json_login_ldap.main' shared autowired service.
     *
     * @return \App\Security\Ldap\AppCheckLdapCredentialsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/ldap/Security/CheckLdapCredentialsListener.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/Ldap/AppCheckLdapCredentialsListener.php';

        return $container->privates['security.listener.json_login_ldap.main'] = new \App\Security\Ldap\AppCheckLdapCredentialsListener(new \Symfony\Component\DependencyInjection\ServiceLocator(['Symfony\\Component\\Ldap\\Ldap' => function () use ($container) {
            return ($container->privates['Symfony\\Component\\Ldap\\Ldap'] ?? $container->load('getLdapService'));
        }]));
    }
}
