<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Authentication\Controller\SecurityController' shared autowired service.
     *
     * @return \App\Authentication\Controller\SecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Authentication/Controller/SecurityController.php';

        $container->services['App\\Authentication\\Controller\\SecurityController'] = $instance = new \App\Authentication\Controller\SecurityController(($container->privates['App\\Authentication\\LegacyHandler\\Authentication'] ?? $container->getAuthenticationService()), ($container->services['session'] ?? $container->getSessionService()));

        $instance->setContainer(($container->privates['.service_locator.BgN1Ddd'] ?? $container->load('get_ServiceLocator_BgN1DddService'))->withContext('App\\Authentication\\Controller\\SecurityController', $container));

        return $instance;
    }
}
