<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsItemResolverService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Statistics\Resolver\StatisticsItemResolver' shared autowired service.
     *
     * @return \App\Statistics\Resolver\StatisticsItemResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/GraphQl/Resolver/QueryItemResolverInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/Resolver/StatisticsItemResolver.php';

        return $container->privates['App\\Statistics\\Resolver\\StatisticsItemResolver'] = new \App\Statistics\Resolver\StatisticsItemResolver(($container->privates['App\\Statistics\\Service\\StatisticsManager'] ?? $container->load('getStatisticsManagerService')));
    }
}
