<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_SuccessHandler_Main_SamlService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authentication.success_handler.main.saml' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\CustomAuthenticationSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-http/Authentication/AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-http/Authentication/CustomAuthenticationSuccessHandler.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-http/Authentication/DefaultAuthenticationSuccessHandler.php';
        include_once \dirname(__DIR__, 3).'/vendor/hslavich/oneloginsaml-bundle/Security/Http/Authentication/SamlAuthenticationSuccessHandler.php';

        return $container->privates['security.authentication.success_handler.main.saml'] = new \Symfony\Component\Security\Http\Authentication\CustomAuthenticationSuccessHandler(new \Hslavich\OneloginSamlBundle\Security\Http\Authentication\SamlAuthenticationSuccessHandler(($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService'))), ['login_path' => 'saml_login', 'always_use_default_target_path' => true, 'default_target_path' => '/', 'target_path_parameter' => '_target_path', 'use_referer' => false], 'main');
    }
}
