<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_EncoderFactory_GenericService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.encoder_factory.generic' shared service.
     *
     * @return \Symfony\Component\Security\Core\Encoder\EncoderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-core/Encoder/EncoderFactoryInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-core/Encoder/EncoderFactory.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-core/Encoder/PasswordEncoderInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-core/Encoder/BasePasswordEncoder.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/LegacyPasswordEncoder.php';

        $a = new \App\Security\LegacyPasswordEncoder();

        return $container->privates['security.encoder_factory.generic'] = new \Symfony\Component\Security\Core\Encoder\EncoderFactory(['app_encoder' => $a, 'App\\Module\\Users\\Entity\\User' => $a]);
    }
}
