<?php

namespace ContainerGRi2xj9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeImagesItemDataProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Themes\DataProvider\ThemeImagesItemDataProvider' shared autowired service.
     *
     * @return \App\Themes\DataProvider\ThemeImagesItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Themes/DataProvider/ThemeImagesItemDataProvider.php';

        return $container->privates['App\\Themes\\DataProvider\\ThemeImagesItemDataProvider'] = new \App\Themes\DataProvider\ThemeImagesItemDataProvider(($container->privates['App\\Themes\\Service\\ThemeImageService'] ?? $container->load('getThemeImageServiceService')));
    }
}
