apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suitecrm.fullname" . }}
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "suitecrm.labels" . | nindent 8 }}
        component: app
        route-ingress: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: SAML_IDP_ENTITY_ID
              value: https://{{.Values.global.ssoDomain}}/auth/realms/{{.Values.global.ssoRealm}}
            - name: SAML_ISP_SSO_URL
              value: >-
                https://{{.Values.global.ssoDomain}}/auth/realms/{{.Values.global.ssoRealm}}/protocol/saml
            - name: SAML_IDP_LOGOUT_URL
              value: >-
                https://{{.Values.global.ssoDomain}}/auth/realms/{{.Values.global.ssoRealm}}/protocol/saml
            - name: SAML_IDP_X509
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.suitecrmSecretName }}
                  key: sso-idp-x509
            - name: SAML_SP_ENTITY_ID
              value: {{.Values.global.ssoClientid}}
            - name: SAML_SP_ASSERTION_URL
              value: >-
                https://{{.Values.global.suitecrmHost}}/saml/acs
            - name: SAML_SP_SINGLE_LOGOUT
              value: >-
                https://{{.Values.global.suitecrmHost}}/saml/logout
            - name: SAML_SP_BASE_URL
              value: https://{{.Values.global.suitecrmHost}}/saml
            - name: AUTH_TYPE
              value: saml
            - name: SAML_AUTO_CREATE
              value: disabled
            - name: SAML_USERNAME_ATTRIBUTE
              value: idir_username
            - name: SAML_USE_ATTRIBUTE_FRIENDLY_NAME
              value: 'false'
            - name: SAML_SP_PRIVATE_KEY
              value: placeholder-value
            - name: SAML_SP_X509
              value: placeholder-value
            - name: SUITE_DB_HOST
              value: suitecrm-mariadb-galera
            - name: SUITE_DB_USER
              value: {{ index (index (index .Values "mariadb-galera") "db") "user" }}
            - name: SUITE_DB_PASSW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.databaseSecretName}}
                  key: mariadb-password
            - name: SUITE_DB_NAME
              value: {{ index (index (index .Values "mariadb-galera") "db") "name" }}
            - name: SUITE_DB_PORT
              value: '3306'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.suitecrmSecretName }}
                  key: database-url
            - name: SESSION_SAVE_HANDLER
              value: rediscluster
            - name: SESSION_SAVE_PATH
              value: 'seed[]=tcp://suitecrm-redis-cluster-headless:6379&timeout=2&read_timeout=2'
            - name: SUITECRM_URL
              value: {{.Values.global.suitecrmHost}}
            - name: SUITECRM_ADMIN_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.suitecrmSecretName }}
                  key: suitecrm-admin-password
            - name: OAUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.suitecrmSecretName }}
                  key: oauth-key
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /auth
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /auth
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
