apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suitecrm.fullname" . }}
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "suitecrm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "suitecrm.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: APACHE_RUN_USER
              value: root
            - name: SAML_IDP_ENTITY_ID
              value: https://{{.Values.Secrets.sso_domain}}/auth/realms/{{.Values.Secrets.sso_realm}}
            - name: SAML_ISP_SSO_URL
              value: >-
                https://{{.Values.Secrets.sso_domain}}/auth/realms/{{.Values.Secrets.sso_realm}}/protocol/saml
            - name: SAML_IDP_LOGOUT_URL
              value: >-
                https://{{.Values.Secrets.sso_domain}}/auth/realms/{{.Values.Secrets.sso_realm}}/protocol/saml
            - name: SAML_IDP_X509
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: SAML_IDP_X509
            - name: SAML_SP_ENTITY_ID
              value: {{.Values.Secrets.sso_clientid}}
            - name: SAML_SP_ASSERTION_URL
              value: >-
                https://{{.Values.Secrets.suitecrmhost}}/saml/acs
            - name: SAML_SP_SINGLE_LOGOUT
              value: >-
                https://{{.Values.Secrets.suitecrmhost}}/saml/logout
            - name: SAML_SP_BASE_URL
              value: https://{{.Values.Secrets.suitecrmhost}}/saml
            - name: AUTH_TYPE
              value: saml
            - name: SAML_AUTO_CREATE
              value: disabled
            - name: SAML_USERNAME_ATTRIBUTE
              value: idir_username
            - name: SAML_USE_ATTRIBUTE_FRIENDLY_NAME
              value: 'false'
            - name: SAML_SP_PRIVATE_KEY
              value: placeholder-value
            - name: SAML_SP_X509
              value: placeholder-value
            - name: SUITE_DB_HOST
              value: suitecrm-mariadb-galera
            - name: SUITE_DB_USER
              value: {{ index (index (index .Values "mariadb-galera") "db") "user" }}
            - name: SUITE_DB_PASSW
              valueFrom:
                secretKeyRef:
                  name: suitecrm-mariadb-galera
                  key: mariadb-password
            - name: SUITE_DB_NAME
              value: cb_suitecrm
            - name: SUITE_DB_PORT
              value: '3306'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: DATABASE_URL
            - name: SESSION_SAVE_HANDLER
              value: rediscluster
            - name: SESSION_SAVE_PATH
              value: 'seed[]=tcp://suitecrm-redis-cluster-headless:6379&timeout=2&read_timeout=2'
            - name: SUITECRM_URL
              value: {{.Values.Secrets.suitecrmhost}}
            - name: SUITECRM_ADMIN_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: SUITECRM_PASSWORD
            - name: OAUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: OAUTH_KEY
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8181
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
