{{- if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - {}
  rules:
    -
      host: "{{tpl .Values.ingress.hostname .}}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.ingress.port }}
{{- end }}