kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "suitecrm.fullname" . }}-deny-by-default
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  ingress: []
  podSelector: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "suitecrm.fullname" . }}-allow-from-openshift-ingress
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  podSelector:
    route-ingress: true
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "suitecrm.fullname" . }}-allow-app-to-db
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mariadb-galera
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              component: app
      ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 4567
        - protocol: TCP
          port: 4568
        - protocol: TCP
          port: 4444
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "suitecrm.fullname" . }}-allow-cron-to-db
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mariadb-galera
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              component: cron
      ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 4567
        - protocol: TCP
          port: 4568
        - protocol: TCP
          port: 4444
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "suitecrm.fullname" . }}-allow-backup-to-db
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mariadb-galera
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: backup-storage
      ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 4567
        - protocol: TCP
          port: 4568
        - protocol: TCP
          port: 4444
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "suitecrm.fullname" . }}-allow-app-to-redis
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              component: app
      ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 16379