---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  DATABASE_URL: mysql://{{.Values.Secrets.mariadbuser}}:{{ .Values.Secrets.mariadbpwd }}@suitecrm-mariadb-galera/{{.Values.Secrets.mariadbname}}
  SAML_IDP_X509: {{ .Values.Secrets.sso_idp_x509 }}
  SUITECRM_PASSWORD: {{ .Values.Secrets.suitecrmadminpwd }}
  OAUTH_KEY: {{ .Values.Secrets.oauthkey }}
type: Opaque
