---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  DATABASE_URL: mysql://{{ index (index (index .Values "mariadb-galera") "db") "user" }}:{{ index (index (index .Values "mariadb-galera") "db") "password" }}@suitecrm-mariadb-galera/{{ index (index (index .Values "mariadb-galera") "db") "name" }}
  SAML_IDP_X509: {{ .Values.Secrets.sso_idp_x509 }}
  SUITECRM_PASSWORD: {{ .Values.Secrets.suitecrmadminpwd }}
  OAUTH_KEY: {{ .Values.Secrets.oauthkey }}
type: Opaque
