apiVersion: v1
kind: Service
metadata:
  name: {{ include "suitecrm.fullname" . }}
  labels:
    {{- include "suitecrm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: 8143-tcp
      protocol: TCP
      port: 8143
      targetPort: 8143
    - name: 8181-tcp
      protocol: TCP
      port: 8181
      targetPort: 8181
  selector:
    component: app


