<?php

$dictionary['Contact']['fields']['advocase_asq_consent_c'] = array(
  'name' => 'advocase_asq_consent_c',
  'vname' => 'LBL_ADVOCASE_ASQ_CONSENT',
  'type' => 'bool',
  'required' => false,
  'len' => '255',
  'default' => '0',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'reportable' => true,
  'unified_search' => false,
  'audited' => false,
);

$dictionary['Contact']['fields']['advocase_clbl_eligible_c'] = array(
  'name' => 'advocase_clbl_eligible_c',
  'vname' => 'LBL_ADVOCASE_CLBL_ELIGIBLE',
  'type' => 'enum',
  'required' => true,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_clbl_eligible_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'reportable' => true,
  'unified_search' => false,
  'audited' => false,
);

$dictionary['Contact']['fields']['advocase_contact_city_c'] = array(
  'name' => 'advocase_contact_city_c',
  'vname' => 'LBL_ADVOCASE_CONTACT_CITY_C',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_city_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Contact']['fields']['advocase_contact_region_c'] = array(
  'name' => 'advocase_contact_region_c',
  'vname' => 'LBL_ADVOCASE_CONTACT_REGION',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_contact_region_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'importable' => true,
  'reportable' => true,
  'audited' => false,
  'unified_search' => false,
);

$dictionary['Contact']['fields']['advocase_contact_type_c'] = array(
  'name' => 'advocase_contact_type_c',
  'vname' => 'LBL_ADVOCASE_CONTACT_TYPE',
  'type' => 'enum',
  'required' => true,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_contact_type_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'importable' => true,
  'reportable' => true,
  'audited' => false,
  'unified_search' => false,
);

$dictionary['Contact']['fields']['advocase_email_c'] = array(
  'name' => 'advocase_email_c',
  'vname' => 'LBL_ADVOCASE_EMAIL_C',
  'type' => 'varchar',
  'required' => false,
  'default' => '',
  'len' => '255',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'importable' => true,
  'reportable' => true,
  'audited' => false,
  'unified_search' => false,
);

$dictionary['Contact']['fields']['advocase_gsa_level_c'] = array(
  'name' => 'advocase_gsa_level_c',
  'vname' => 'LBL_ADVOCASE_GSA_LEVEL',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_gsa_level_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'importable' => true,
  'reportable' => true,
  'audited' => false,
  'unified_search' => false,
);

$dictionary['Contact']['fields']['advocase_individual_age_c'] = array(
  'name' => 'advocase_individual_age_c',
  'vname' => 'LBL_ADVOCASE_INDIVIDUAL_AGE',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_individual_age_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'importable' => true,
  'reportable' => true,
  'audited' => false,
  'unified_search' => false,
);

$dictionary['Contact']['fields']['advocase_legal_agreement_c'] = array(
  'name' => 'advocase_legal_agreement_c',
  'vname' => 'LBL_ADVOCASE_LEGAL_AGREEMENT',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_legal_agreement_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'importable' => true,
  'reportable' => true,
  'audited' => false,
  'unified_search' => false,
);

$dictionary['Contact']['fields']['advocase_notes_c'] = array(
  'name' => 'advocase_notes_c',
  'vname' => 'LBL_ADVOCASE_NOTES',
  'type' => 'text',
  'required' => false,
  'default' => '',
  'rows' => '6',
  'cols' => '20',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'importable' => true,
  'reportable' => true,
  'audited' => false,
  'unified_search' => false,
);

$dictionary['Contact']['fields']['advocase_other_contact_type_c'] = array(
  'name' => 'advocase_other_contact_type_c',
  'vname' => 'LBL_ADVOCASE_OTHER_CONTACT_TYPE',
  'type' => 'varchar',
  'required' => false,
  'default' => '',
  'len' => '255',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'importable' => true,
  'reportable' => true,
  'audited' => false,
  'unified_search' => false,
);