parameters:
  ui:
    alert_timeout: 3
    user_preferences_save_delay: 500
    loading_display_delay: 900
    table_loading_display_delay: 800
    modal_buttons_collapse_breakpoint: 4
    list_max_entries_per_record_thread: 10
    tinymce:
      edit:
        base_url: './dist/tinymce'
        suffix: '.min'
        modelEvents: 'change'
        ignoreEvents: "onKeyDown,onKeyPress,onKeyUp,onSelectionChange"
        height: 500
        deprecation_warnings: false
        menubar: false
        plugins:
          - 'advlist autolink lists link image charmap print preview anchor'
          - 'searchreplace visualblocks code fullscreen'
          - 'insertdatetime media table paste code help wordcount'
        toolbar: 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify |  bullist numlist outdent indent | removeformat | help'
        toolbar_mode: 'floating'
        mobile:
          theme: 'mobile'
      detail:
        base_url: './dist/tinymce'
        suffix: '.min'
        deprecation_warnings: false
        readonly: true
        toolbar: false
        menubar: false
        statusbar: false
        inline: true
    navigation_max_module_recently_viewed: 5
    navigation_max_module_favorites: 5
    subpanel_max_height: 620
    listview_max_height: 0
    record_modal_max_height: 620
    inline_confirmation_loading_delay: 300
    displayed_quick_filters:
      XSmall: 0
      Small: 4
      Medium: 2
      Large: 3
      XLarge: 5
    quick_filters_breakdown_threshold:
      XSmall: 0
      Small: 4
      Medium: 2
      Large: 3
      XLarge: 5
    enable_quick_filters:
      XSmall: false
      Small: true
      Medium: true
      Large: true
      XLarge: true
    quick_filters_breakdown_screen_sizes:
      XSmall: true
      Small: true
      Medium: false
      Large: false
      XLarge: false
    widget_swap_screen_sizes:
      XSmall: true
      Small: true
      Medium: false
      Large: false
      XLarge: false
