# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb-galera:
    image: bitnami/mariadb-galera:latest
    ports:
      - '3307:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - MARIADB_PASSWORD=bitnami123
    volumes:
      - './db:/bitnami/mariadb'
    networks:
      - suitecrm

networks:
  suitecrm: