# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb-galera:
    image: bitnami/mariadb-galera:latest
    ports:
      - '3307:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - MARIADB_PASSWORD=bitnami123
    volumes:
      - './db:/bitnami/mariadb'
    networks:
      - suitecrm

  suitecrm:
    build:
      context: advocase-image
      dockerfile: Dockerfile
    ports:
      - '80:8181'
      - '443:8143'
    environment:
      - DATABASE_URL="mysql://bn_suitecrm:bitnami123@mariadb-galera/bitnami_suitecrm"
      - SUITE_DB_HOST="mariadb-galera"
      - SUITE_DB_USER="bn_suitecrm"
      - SUITE_DB_NAME="bitnami_suitecrm"
      - SUITE_DB_PASSW="bitnami123"
      - SUITE_DB_PORT=3306
      - SESSION_SAVE_HANDLER="files"
      - SESSION_SAVE_PATH="/tmp"
    depends_on:
      - mariadb-galera
    networks:
      - suitecrm

networks:
  suitecrm: