# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.3
    ports:
      - '3307:3306'
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes # Official name for ALLOW_EMPTY_PASSWORD
      - MARIADB_USER=mariadb_suitecrm
      - MARIADB_DATABASE=mariadb_suitecrm
      - MARIADB_PASSWORD=mariadb123
    volumes:
      - './db:/var/lib/mysql'
    networks:
      - suitecrm

networks:
  suitecrm: