kind: Service
apiVersion: v1
metadata:
  name: cbsuitecrm
  namespace: d1f241-dev
  labels:
    deployment: cbsuitecrm
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  ports:
    - name: 8181-tcp
      protocol: TCP
      port: 8181
      targetPort: 8181
  selector:
    deployment: cbsuitecrm
