kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cbsuitecrm-uploads-shared
  namespace: d1f241-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
