## helm dependency update ./suitecrm
## helm install suitecrm ./suitecrm/ -f <customfile.yaml>
## To generate a new one, run on any host> php -r 'echo base64_encode(random_bytes(32)), PHP_EOL;'

Secrets:
  redispwd: "changeme"
  mariadbpwd: "changeme
  suitecrmhost: "myurl.domain"
  sso_domain: "keycloakserver"
  sso_realm: "standard"
  suitecrmadminpwd: "suitecrmadminpassword"
  sso_clientid: "keycloakclient"
  sso_idp_x509: "keycloakidp509cert"
  oauthkey:  "selfgeneratedoauthkey"

mariadb-galera:
  replicaCount: 1
  persistence:
    size: 2G
  enabled: true
  galera:
    mariabackup:
      password: sameasabove
  rootUser:
    password: changeme
  db:
    password: sameasabove

redis-cluster:
  global:
    redis:
      password: "sameasabove"
      
image:
  tag: "dev"
