parameters:
  module.base_actions:
    default:
      actions:
        index: &index
          key: index
          labelKey: LBL_LISTVIEW
          acl:
            - list
        list: *index
        view: &view
          key: view
          labelKey: LBL_DETAILVIEW
          acl:
            - view
        record: *view
        create:
          key: create
          labelKey: LBL_NEW
          acl:
            - edit
        edit:
          key: edit
          labelKey: LBL_EDIT
          acl:
            - edit
        save:
          key: save
          labelKey: LBL_SAVE_BUTTON_LABEL
          acl:
            - edit
        saveNew:
          key: saveNew
          labelKey: LBL_SAVE_BUTTON_LABEL
          acl:
            - edit
        delete:
          key: delete
          labelKey: LBL_DELETE
          asyncProcess: true
          acl:
            - delete
        duplicate:
          key: duplicate
          labelKey: LBL_DUPLICATE_BUTTON
          asyncProcess: true
          acl:
            - export
            - edit
        audit:
          key: audit
          labelKey: LNK_VIEW_CHANGE_LOG
          asyncProcess: true
          availability:
            - audited
            - acls
        merge-records:
          key: merge-records
          labelKey: LBL_DUP_MERGE
          asyncProcess: true
          availability:
            - duplicate-merge
            - acls
          acl:
            - edit
            - delete
        export:
          key: export
          labelKey: LBL_EXPORT
          acl:
            - export
        massupdate:
          key: massupdate
          labelKey: LBL_MASS_UPDATE
          availability:
            - acls
            - massupdate
          acl:
            - massupdate
