<?php

$dictionary['Case']['fields']['adovcase_case_agencies_c'] = array(
  'name' => 'adovcase_case_agencies_c',
  'vname' => 'LBL_ADOVCASE_CASE_AGENCIES',
  'type' => 'multienum',
  'required' => false,
  'default' => NULL,
  'options' => 'adovcase_case_agencies_list',
  'isMultiSelect' => true,
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_asq_action_c'] = array(
  'name' => 'advocase_asq_action_c',
  'vname' => 'LBL_ADVOCASE_ASQ_ACTION',
  'type' => 'multienum',
  'required' => false,
  'default' => NULL,
  'options' => 'advocase_asq_action_list',
  'isMultiSelect' => true,
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_call_log_c'] = array(
  'name' => 'advocase_call_log_c',
  'vname' => 'LBL_ADVOCASE_CALL_LOG',
  'type' => 'text',
  'required' => true,
  'default' => '',
  'rows' => '6',
  'cols' => '20',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_action_date_c'] = array(
  'name' => 'advocase_case_action_date_c',
  'vname' => 'LBL_ADVOCASE_CASE_ACTION_DATE',
  'type' => 'date',
  'required' => true,
  'default' => '',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
  'enable_range_search' => false,
);

$dictionary['Case']['fields']['advocase_case_city_c'] = array(
  'name' => 'advocase_case_city_c',
  'vname' => 'LBL_ADVOCASE_CASE_CITY_C',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_city_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_issue_1_c'] = array(
  'name' => 'advocase_case_issue_1_c',
  'vname' => 'LBL_ADVOCASE_CASE_ISSUE_1',
  'type' => 'enum',
  'required' => true,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_case_issues_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_issue_2_c'] = array(
  'name' => 'advocase_case_issue_2_c',
  'vname' => 'LBL_ADVOCASE_CASE_ISSUE_2',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_case_issues_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_issue_3_c'] = array(
  'name' => 'advocase_case_issue_3_c',
  'vname' => 'LBL_ADVOCASE_CASE_ISSUE_3',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_case_issues_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_issue_4_c'] = array(
  'name' => 'advocase_case_issue_4_c',
  'vname' => 'LBL_ADVOCASE_CASE_ISSUE_4',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_case_issues_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_issue_5_c'] = array(
  'name' => 'advocase_case_issue_5_c',
  'vname' => 'LBL_ADVOCASE_CASE_ISSUE_5',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_case_issues_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_other_issue_c'] = array(
  'name' => 'advocase_case_other_issue_c',
  'vname' => 'LBL_ADVOCASE_CASE_OTHER_ISSUE',
  'type' => 'varchar',
  'required' => false,
  'default' => '',
  'len' => '255',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_other_none_c'] = array(
  'name' => 'advocase_case_other_none_c',
  'vname' => 'LBL_ADVOCASE_CASE_OTHER_NONE',
  'type' => 'varchar',
  'required' => false,
  'default' => '',
  'len' => '255',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_case_region_c'] = array(
  'name' => 'advocase_case_region_c',
  'vname' => 'LBL_ADVOCASE_CASE_REGION',
  'type' => 'enum',
  'required' => true,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_case_region_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_communication_date_c'] = array(
  'name' => 'advocase_communication_date_c',
  'vname' => 'LBL_ADVOCASE_COMMUNICATION_DATE',
  'type' => 'date',
  'required' => true,
  'default' => '',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
  'enable_range_search' => false,
);

$dictionary['Case']['fields']['advocase_communication_type_c'] = array(
  'name' => 'advocase_communication_type_c',
  'vname' => 'LBL_ADVOCASE_COMMUNICATION_TYPE',
  'type' => 'enum',
  'required' => true,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_communication_type_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_oasq_awareness_c'] = array(
  'name' => 'advocase_oasq_awareness_c',
  'vname' => 'LBL_ADVOCASE_OASQ_AWARENESS',
  'type' => 'enum',
  'required' => false,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_oasq_awareness_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_oasq_mandate_c'] = array(
  'name' => 'advocase_oasq_mandate_c',
  'vname' => 'LBL_ADVOCASE_OASQ_MANDATE',
  'type' => 'enum',
  'required' => true,
  'default' => NULL,
  'len' => '100',
  'options' => 'advocase_oasq_mandate_list',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);

$dictionary['Case']['fields']['advocase_other_comm_type_c'] = array(
  'name' => 'advocase_other_comm_type_c',
  'vname' => 'LBL_ADVOCASE_OTHER_COMM_TYPE',
  'type' => 'varchar',
  'required' => false,
  'default' => '',
  'len' => '255',
  'studio' => 'visible',
  'inline_edit' => '1',
  'duplicate_merge' => 'disabled',
  'massupdate' => '0',
  'audited' => false,
  'importable' => true,
  'reportable' => true,
  'unified_search' => false,
);
