kind: ConfigMap
  apiVersion: v1
  metadata:
    name: {{ include "backup-storage-cron.fullname" . }}-config
    labels:
      cronjob: {{ include "backup-storage-cron.fullname" . }}
  data:
    DATABASE_SERVICE_NAME: {{ .Values.env.DATABASE_SERVICE_NAME }}
    DEFAULT_PORT: {{ .Values.env.DEFAULT_PORT }}
    POSTGRESQL_DATABASE: {{ .Values.env.POSTGRESQL_DATABASE }}
    BACKUP_STRATEGY: {{ .Values.env.BACKUP_STRATEGY }}
    RETENTION.NUM_BACKUPS: {{ .Values.env.NUM_BACKUPS }}
    RETENTION.DAILY_BACKUPS: {{ .Values.env.DAILY_BACKUPS }}
    RETENTION.WEEKLY_BACKUPS: {{ .Values.env.WEEKLY_BACKUPS }}
    RETENTION.MONTHLY_BACKUPS: {{ .Values.env.MONTHLY_BACKUPS }}
    ENVIRONMENT_FRIENDLY_NAME: {{ .Values.env.ENVIRONMENT_FRIENDLY_NAME }}
    ENVIRONMENT_NAME: {{ .Values.env.ENVIRONMENT_NAME }}