apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-storage-cron-config
  labels:
    cronjob: backup-storage-cron
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}