kind: "CronJob"
  apiVersion: "batch/v1"
  metadata:
    name: {{ include "backup-storage-cron.fullname" . }}-backup
    labels:
      cronjob: {{ include "backup-storage-cron.fullname" . }}
  spec:
    schedule: {{ .Values.cron.schedule }}
    concurrencyPolicy: "Forbid"
    successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
    failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
    jobTemplate:
      metadata:
        labels:
          cronjob: {{ .include "backup-storage-cron-fullname" . }}-backup-cronjob
      spec:
        backoffLimit: {{ .Values.cron.backoffLimit }}
        template:
          metadata:
            labels:
              cronjob: {{ .include "backup-storage-cron.fullname" . }}
          spec:
            containers:
              - name: {{ .include "backup-storage-cron.fullname" }}-cronjob
                image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
                command:
                  - "/bin/bash"
                  - "-c"
                  - "/backup.sh -1"
                volumeMounts:
                  - mountPath: {{ .Values.env.BACKUP_DIR }}
                    name: "backup"
                env:
                  - name: BACKUP_DIR
                    value: {{ .Values.env.BACKUP_DIR }}
                  - name: BACKUP_STRATEGY
                    valueFrom:
                      configMapKeyRef:
                        name: {{ .include "backup-storage-cron.fullname" . }}-config
                        key: BACKUP_STRATEGY
                  - name: NUM_BACKUPS
                    valueFrom:
                      configMapKeyRef:
                        name: {{ .include "backup-storage-cron.fullname" . }}-config
                        key: RETENTION.NUM_BACKUPS
                        optional: true
                  - name: DAILY_BACKUPS
                    valueFrom:
                      configMapKeyRef:
                        name: {{ .include "backup-storage-cron.fullname" . }}-config
                        key: RETENTION.DAILY_BACKUPS
                        optional: true
                  - name: WEEKLY_BACKUPS
                    valueFrom:
                      configMapKeyRef:
                        name: {{ .include "backup-storage-cron.fullname" . }}-config
                        key: RETENTION.WEEKLY_BACKUPS
                        optional: true
                  - name: MONTHLY_BACKUPS
                    valueFrom:
                      configMapKeyRef:
                        name: {{ .include "backup-storage-cron.fullname" . }}-config
                        key: RETENTION.MONTHLY_BACKUPS
                        optional: true
                  - name: DATABASE_SERVICE_NAME
                    valueFrom:
                      configMapKeyRef:
                        name: {{ .include "backup-storage-cron.fullname" . }}-config
                        key: DATABASE_SERVICE_NAME
                  - name: DEFAULT_PORT
                    valueFrom:
                      configMapKeyRef:
                        name: {{ .include "backup-storage-cron.fullname" . }}-config
                        key: DEFAULT_PORT
                        optional: true
                  - name: POSTGRESQL_DATABASE
                    valueFrom:
                      configMapKeyRef:
                        name: {{ .include "backup-storage-cron.fullname" . }}-config
                        key: POSTGRESQL_DATABASE
                  - name: DATABASE_USER
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.db.secretName }}
                        key: {{ .Values.db.usernameKey }}
                  - name: DATABASE_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.db.secretName }}
                        key: {{ .Values.db.passwordKey }}
            volumes:
              - name: {{ template "backup-storage-cron.fullname" $ }}-backup-pvc
                persistentVolumeClaim:
                  claimName: {{ template "backup-storage-cron.fullname" $ }}-backup-pvc
            restartPolicy: "Never"
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 1600
            dnsPolicy: "ClusterFirst"
            serviceAccountName: {{ include "backup-storage-cron.serviceAccountName" . }}
            serviceAccount: {{ include "backup-storage-cron.serviceAccountName" . }}