{{- range $name, $val := .Values.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "backup-storage-cron.fullname" $ }}-{{ $name }}-pvc
  {{- with $.Values.storageAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{ end }}
  labels:
      app: {{ template "backup-storage-cron.name" $ }}
      chart: {{ template "backup-storage-cron.chart" $ }}
      release: {{ $.Release.Name }}
      heritage: {{ $.Release.Service }}
spec:
  accessModes:
    - {{.storageAccessMode}}
  storageClassName: {{.storageClassName}}
  resources:
    requests:
      storage: {{.size}}
---
{{- end }}
