hslavich_onelogin_saml:
  # Basic settings
  idp:
    entityId: '%env(SAML_IDP_ENTITY_ID)%'
    singleSignOnService:
      url: '%env(SAML_ISP_SSO_URL)%'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
    singleLogoutService:
      url: '%env(SAML_IDP_LOGOUT_URL)%'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    x509cert: '%env(SAML_IDP_X509)%'
  sp:
    entityId: '%env(SAML_SP_ENTITY_ID)%'
    assertionConsumerService:
      url: '%env(SAML_SP_ASSERTION_URL)%'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
    singleLogoutService:
      url: '%env(SAML_SP_SINGLE_LOGOUT)%'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    privateKey: '%env(SAML_SP_PRIVATE_KEY)%'
    x509cert: '%env(SAML_SP_X509)%'
  # Optional settings
  baseurl: '%env(SAML_SP_BASE_URL)%'
  strict: true
  debug: true
  security:
    nameIdEncrypted: false
    authnRequestsSigned: false
    logoutRequestSigned: false
    logoutResponseSigned: false
    wantMessagesSigned: false
    wantAssertionsSigned: false
    wantNameIdEncrypted: false
    requestedAuthnContext: true
    signMetadata: false
    wantXMLValidation: true
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
  contactPerson:
    technical:
      givenName: 'Tech User'
      emailAddress: 'techuser@example.com'
    support:
      givenName: 'Support User'
      emailAddress: 'supportuser@example.com'
  organization:
    en:
      name: 'Example'
      displayname: 'Example'
      url: 'http://example.com'
