parameters:
  legacy.cache_reset_actions:
    users:
      - edit
    administration:
      - repair
      - UpgradeWizard
      - ConfigureTabs
      - Locale
      - PasswordManager
      - ThemeSettings
      - Languages
    module-builder:
      - index
    configurator:
      - edit
    currencies:
      - index
    security-groups:
      - index
      - config
    studio:
      - wizard
