parameters:
  massupdate:
    excludedFields:
      - date_modified
      - date_entered
      - created_by
      - modified_user_id
      - deleted
      - modified_by_name
      - assigned_user_id
    activeByDefaultRelateModules:
      - Accounts
      - Contacts
      - Users
      - Employee
      - Releases
    activeByDefaultFields:
      - reports_to_name
    activeByDefaultTypes:
      - parent
      - bool
      - enum
      - dynamicenum
      - multienum
      - radioenum
      - datetimecombo
      - datetime
      - date
    includedTypes:
      - relate
      - parent
      - int
      - bool
      - enum
      - dynamicenum
      - multienum
      - radioenum
      - datetimecombo
      - datetime
      - date
