parameters:
  # Adds a fallback in case the env is not set.
  env(DATABASE_URL): ''

doctrine:
  dbal:
    url: '%env(DATABASE_URL)%'
    driver: pdo_mysql
    charset: UTF8
    auto_commit: false
    schema_filter: '/^(users|migration_versions|)$/'
    default_table_options:
      charset: utf8
      collate: utf8_unicode_ci
    logging: "%kernel.debug%"
    profiling: "%kernel.debug%"

  orm:
    auto_generate_proxy_classes: false
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/core'
        prefix: 'App'
        alias: App
