doctrine_migrations:
  migrations_paths:
    'App\Migrations': '%kernel.project_dir%/core/backend/Migrations'
  storage:
    table_storage:
      table_name: 'migration_versions'
      version_column_name: 'version'
      version_column_length: 1024
      executed_at_column_name: 'executed_at'
  organize_migrations: false
  custom_template: ~
  all_or_nothing: false

  services:
    'Doctrine\Migrations\Version\MigrationFactory': 'App\Install\Service\Migrations\MigrationFactoryDecorator'
