hslavich_onelogin_saml:
  # Basic settings
  idp:
    entityId: 'https://id.example.com/saml2/idp/metadata.php'
    singleSignOnService:
      url: 'https://id.example.com/saml2/idp/SSOService.php'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    singleLogoutService:
      url: 'https://id.example.com/saml2/idp/SingleLogoutService.php'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    x509cert: 'MIIC...'
  sp:
    entityId: 'https://myapp.com/saml/metadata'
    assertionConsumerService:
      url: 'https://myapp.com/saml/acs'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
    singleLogoutService:
      url: 'https://myapp.com/saml/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    privateKey: '/var/www/html/docroot/certs/key.pem'
  # Optional settings
  baseurl: 'https://myapp.com/saml/'
  strict: true
  debug: true
  security:
    nameIdEncrypted: false
    authnRequestsSigned: false
    logoutRequestSigned: false
    logoutResponseSigned: false
    wantMessagesSigned: false
    wantAssertionsSigned: false
    wantNameIdEncrypted: false
    requestedAuthnContext: true
    signMetadata: false
    wantXMLValidation: true
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
  contactPerson:
    technical:
      givenName: 'Tech User'
      emailAddress: 'techuser@example.com'
    support:
      givenName: 'Support User'
      emailAddress: 'supportuser@example.com'
  organization:
    en:
      name: 'Example'
      displayname: 'Example'
      url: 'http://example.com'
