kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: suitecrm-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'bcgovsuitecrm:latest'
  resources:
    limits:
      cpu: '1'
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 1Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: docker/Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/SDPR_Case_Management_SuiteCRM.git'
      ref: test
  runPolicy: Serial
