name: Wait for rollout
on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
    secrets:
      licence-plate:
        required: true
      openshift-api:
        required: true
      token:
        required: true

jobs:
  tag:
    name: Wait for rollout in {{ secrets.licence-plate }}-${{ inputs.namespace }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.namespace }}

    steps:
    - name: Log in to OpenShift tools
      uses: redhat-actions/oc-login@v1
      with:
        namespace: ${{ secrets.licence-plate }}-${{ inputs.namespace }}
        openshift_server_url: ${{ secrets.openshift-api }}
        openshift_token: ${{ secrets.token }}

    - name: Wait for rollout
      run: |
        #
        # Parameters: namespace deployment-config
        #
        wait_for_rollout () {
          NAMESPACE_DEPLOY=$1

          STATUS=
          while [ "$STATUS" != "Complete" ]; do
            VERSION=$(oc -n $NAMESPACE_DEPLOY get deployment suitecrm -o json | jq '.status.latestVersion')
            STATUS=$(oc -n $NAMESPACE_DEPLOY rollout history dc/suitecrm | grep ^$VERSION | awk '{ print $2 }')
            WHEN=$(oc -n $NAMESPACE_DEPLOY get replicationcontroller suitecrm-$VERSION --no-headers | awk '{ print $5 }')

            echo "Rollout #$VERSION of suitecrm is \"$STATUS\" $WHEN ago"
            sleep 1
          done
        }

        wait_for_rollout ${{ secrets.licence-plate }}-${{ inputs.tag-to }} $image
