name: Rollout deployment
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      licence-plate:
        required: true
      openshift-api:
        required: true
      token:
        required: true

jobs:
  tag:
    name: Rollout deployment
    runs-on: ubuntu-latest

    steps:
    - name: Log in to OpenShift tools
      uses: redhat-actions/oc-login@v1
      with:
        namespace: ${{ secrets.licence-plate }}-${{ inputs.env }}
        openshift_server_url: ${{ secrets.openshift-api }}
        openshift_token: ${{ secrets.token }}

    - name: Rollout deployment
      run: |
        oc rollout restart deployment/suitecrm
